### ISSUE TITLE
Question re: subbrik indexing in tat

### ISSUE THREAD

**Issue by jlhanson5** [lncd/lncdtools#3]
Hello LNCD Friends,

I was test driving the tat script (thanks for developing those resources!), and had a question about subbrik indexing. I had a NIFTI file with 370 volumes and a censor file with 370 lines, but I keep getting a warning about files being slightly different lengths. 
<img width="1867" alt="Terminal_Output" src="https://github.com/lncd/lncdtools/assets/7240261/acf225d5-7bf2-4dde-a38e-668ff8c8b88c">
(Basically it says `# [Thu 03 Aug 2023 04:35:36 PM EDT] censor: using 368/370 timepoints. (last vol: 369) [/home/jamielh/Volumes/Hanson/External_MRI_Projects/HealthyBrainNetwork/Neuroimaging/BIDS/derivatives/lurie_timeseries/no_aroma/subs/NDARAA306NT2/run-1/censor_file/censor_minus5.1D]`)

BUT, 3dinfo and nedit  suggest my files are the same length. 
<img width="876" alt="Censor_Line_Number" src="https://github.com/lncd/lncdtools/assets/7240261/c48fd7fc-50c5-4584-846b-cc57c82db702">
<img width="1595" alt="BOLD_Count" src="https://github.com/lncd/lncdtools/assets/7240261/f53e9720-d7b5-4115-849c-145b31e01860">

Is there a flag or argument that I should be including (so no volumes are being dropped, etc.?) or is there something else I'm potentially doing incorrectly?

Here's my basic syntax: 
`/home/jamielh/Volumes/Hanson/Resources/lncdtools-0.0.202307242/tat2 /home/jamielh/Volumes/Hanson/External_MRI_Projects/HealthyBrainNetwork/Neuroimaging/BIDS/derivatives/lurie_timeseries/no_aroma/subs/${i}/run-1/bold_trimmed.nii.gz -mask_rel /home/jamielh/Volumes/Hanson/Resources/lncdtools-0.0.202307242/MNI152_T1_2mm_brain_mask_filled_LPI.nii.gz -censor_rel /home/jamielh/Volumes/Hanson/External_MRI_Projects/HealthyBrainNetwork/Neuroimaging/BIDS/derivatives/lurie_timeseries/no_aroma/subs/${i}/run-1/censor_file/censor_minus5.1D -output ${i}_run-1_tat2star_regCen_fil_mask.nii.gz
`

I have checked and compared a few different times, and it looks like all the same length... but still that error. I'm on a pretty plain vanilla Ubuntu (20.04.6 LTS) server and using an older version of AFNI (Precompiled binary linux_openmp_64: Jul  6 2018 (Version AFNI_18.2.04)... I'll update it shortly, but I didn't think the dated AFNI-ness would cause an issue, etc.). Thoughts?

Many thanks in advance,
Jamie.

**Comment by WillForan** [comment]
Ahh I think the show stopping error is when the script tries to use `gitver` (another lncdtool). it's failing b/c the tat2 script isn't in a directory that's tracked by git. I think this can be a quick fix.

FWIW the line
> using 368/370 timepoints. (last vol: 369)
is saying 368 volumes of the total 370 are not censored (2 are). last volume is the 0-based index: 369 is the 370th volume.  (I think these are more useful counts when than one EPI has been combined.)

**Comment by jlhanson5** [comment]
Deep thanks for the help! I think this all makes sense!

After posting I realized that censor note (368/370) wasn't really an error, just an "update" [Sorry for my confusion].

In terms of `gitver`, I didn't add lncdtool to my `$PATH` in this test drive, but I'm presuming if I did that would stop that output/error? 
[the tat script completed, but there was just lots of output... but that's kind of standard with AFNI calls]

**Comment by WillForan** [comment]
Drowning in output is the AFNI way! tat2's not helping there either 

Turns out tat2 was using it's own function for gitver and was still unhappy (now uses external gitver if it's available).

re. error:
 `tat2` is using "strict mode" bash (`set -e`) so it might have bailed/ended early after `gitver` failed (should be fixed now). It's not a huge problem given that it did all the calculations before that line.
BUT it might have failed to clean up the temp files and missed on on writing the provenance info (see `3dNotes *_tat2.nii.gz`).

**Comment by jlhanson5** [comment]
Amazing, deep thanks for all the help! I think everything is moving forward... and now, I'm just looking if different bits (i.e., stricter censor files) improve reliability, etc. 

Thanks again!
